/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as appLayoutRouteImport } from './pages/(app)/_layout'
import { Route as authRegisterIndexRouteImport } from './pages/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './pages/(auth)/login/index'
import { Route as appLayoutNotesIndexRouteImport } from './pages/(app)/_layout.notes/index'
import { Route as appLayoutFinanceIndexRouteImport } from './pages/(app)/_layout.finance/index'
import { Route as appLayoutActivityIndexRouteImport } from './pages/(app)/_layout.activity/index'
import { Route as appLayoutPortfolioStocksIndexRouteImport } from './pages/(app)/_layout.portfolio/stocks/index'
import { Route as appLayoutPortfolioOverviewIndexRouteImport } from './pages/(app)/_layout.portfolio/overview/index'
import { Route as appLayoutPortfolioCryptoIndexRouteImport } from './pages/(app)/_layout.portfolio/crypto/index'
import { Route as appLayoutFinanceWalletIndexRouteImport } from './pages/(app)/_layout.finance/wallet/index'
import { Route as appLayoutFinanceTransactionsIndexRouteImport } from './pages/(app)/_layout.finance/transactions/index'
import { Route as appLayoutFinanceStatisticIndexRouteImport } from './pages/(app)/_layout.finance/statistic/index'
import { Route as appLayoutFinanceCategoriesIndexRouteImport } from './pages/(app)/_layout.finance/categories/index'
import { Route as appLayoutActivityTimerIndexRouteImport } from './pages/(app)/_layout.activity/timer/index'
import { Route as appLayoutActivityLogIndexRouteImport } from './pages/(app)/_layout.activity/log/index'
import { Route as appLayoutActivityCategoriesIndexRouteImport } from './pages/(app)/_layout.activity/categories/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutNotesIndexRoute = appLayoutNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutFinanceIndexRoute = appLayoutFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutActivityIndexRoute = appLayoutActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutPortfolioStocksIndexRoute =
  appLayoutPortfolioStocksIndexRouteImport.update({
    id: '/portfolio/stocks/',
    path: '/portfolio/stocks/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutPortfolioOverviewIndexRoute =
  appLayoutPortfolioOverviewIndexRouteImport.update({
    id: '/portfolio/overview/',
    path: '/portfolio/overview/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutPortfolioCryptoIndexRoute =
  appLayoutPortfolioCryptoIndexRouteImport.update({
    id: '/portfolio/crypto/',
    path: '/portfolio/crypto/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutFinanceWalletIndexRoute =
  appLayoutFinanceWalletIndexRouteImport.update({
    id: '/finance/wallet/',
    path: '/finance/wallet/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutFinanceTransactionsIndexRoute =
  appLayoutFinanceTransactionsIndexRouteImport.update({
    id: '/finance/transactions/',
    path: '/finance/transactions/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutFinanceStatisticIndexRoute =
  appLayoutFinanceStatisticIndexRouteImport.update({
    id: '/finance/statistic/',
    path: '/finance/statistic/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutFinanceCategoriesIndexRoute =
  appLayoutFinanceCategoriesIndexRouteImport.update({
    id: '/finance/categories/',
    path: '/finance/categories/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutActivityTimerIndexRoute =
  appLayoutActivityTimerIndexRouteImport.update({
    id: '/activity/timer/',
    path: '/activity/timer/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutActivityLogIndexRoute =
  appLayoutActivityLogIndexRouteImport.update({
    id: '/activity/log/',
    path: '/activity/log/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutActivityCategoriesIndexRoute =
  appLayoutActivityCategoriesIndexRouteImport.update({
    id: '/activity/categories/',
    path: '/activity/categories/',
    getParentRoute: () => appLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/activity': typeof appLayoutActivityIndexRoute
  '/finance': typeof appLayoutFinanceIndexRoute
  '/notes': typeof appLayoutNotesIndexRoute
  '/activity/categories': typeof appLayoutActivityCategoriesIndexRoute
  '/activity/log': typeof appLayoutActivityLogIndexRoute
  '/activity/timer': typeof appLayoutActivityTimerIndexRoute
  '/finance/categories': typeof appLayoutFinanceCategoriesIndexRoute
  '/finance/statistic': typeof appLayoutFinanceStatisticIndexRoute
  '/finance/transactions': typeof appLayoutFinanceTransactionsIndexRoute
  '/finance/wallet': typeof appLayoutFinanceWalletIndexRoute
  '/portfolio/crypto': typeof appLayoutPortfolioCryptoIndexRoute
  '/portfolio/overview': typeof appLayoutPortfolioOverviewIndexRoute
  '/portfolio/stocks': typeof appLayoutPortfolioStocksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/activity': typeof appLayoutActivityIndexRoute
  '/finance': typeof appLayoutFinanceIndexRoute
  '/notes': typeof appLayoutNotesIndexRoute
  '/activity/categories': typeof appLayoutActivityCategoriesIndexRoute
  '/activity/log': typeof appLayoutActivityLogIndexRoute
  '/activity/timer': typeof appLayoutActivityTimerIndexRoute
  '/finance/categories': typeof appLayoutFinanceCategoriesIndexRoute
  '/finance/statistic': typeof appLayoutFinanceStatisticIndexRoute
  '/finance/transactions': typeof appLayoutFinanceTransactionsIndexRoute
  '/finance/wallet': typeof appLayoutFinanceWalletIndexRoute
  '/portfolio/crypto': typeof appLayoutPortfolioCryptoIndexRoute
  '/portfolio/overview': typeof appLayoutPortfolioOverviewIndexRoute
  '/portfolio/stocks': typeof appLayoutPortfolioStocksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_layout': typeof appLayoutRouteWithChildren
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(app)/_layout/activity/': typeof appLayoutActivityIndexRoute
  '/(app)/_layout/finance/': typeof appLayoutFinanceIndexRoute
  '/(app)/_layout/notes/': typeof appLayoutNotesIndexRoute
  '/(app)/_layout/activity/categories/': typeof appLayoutActivityCategoriesIndexRoute
  '/(app)/_layout/activity/log/': typeof appLayoutActivityLogIndexRoute
  '/(app)/_layout/activity/timer/': typeof appLayoutActivityTimerIndexRoute
  '/(app)/_layout/finance/categories/': typeof appLayoutFinanceCategoriesIndexRoute
  '/(app)/_layout/finance/statistic/': typeof appLayoutFinanceStatisticIndexRoute
  '/(app)/_layout/finance/transactions/': typeof appLayoutFinanceTransactionsIndexRoute
  '/(app)/_layout/finance/wallet/': typeof appLayoutFinanceWalletIndexRoute
  '/(app)/_layout/portfolio/crypto/': typeof appLayoutPortfolioCryptoIndexRoute
  '/(app)/_layout/portfolio/overview/': typeof appLayoutPortfolioOverviewIndexRoute
  '/(app)/_layout/portfolio/stocks/': typeof appLayoutPortfolioStocksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/activity'
    | '/finance'
    | '/notes'
    | '/activity/categories'
    | '/activity/log'
    | '/activity/timer'
    | '/finance/categories'
    | '/finance/statistic'
    | '/finance/transactions'
    | '/finance/wallet'
    | '/portfolio/crypto'
    | '/portfolio/overview'
    | '/portfolio/stocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/activity'
    | '/finance'
    | '/notes'
    | '/activity/categories'
    | '/activity/log'
    | '/activity/timer'
    | '/finance/categories'
    | '/finance/statistic'
    | '/finance/transactions'
    | '/finance/wallet'
    | '/portfolio/crypto'
    | '/portfolio/overview'
    | '/portfolio/stocks'
  id:
    | '__root__'
    | '/'
    | '/(app)/_layout'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(app)/_layout/activity/'
    | '/(app)/_layout/finance/'
    | '/(app)/_layout/notes/'
    | '/(app)/_layout/activity/categories/'
    | '/(app)/_layout/activity/log/'
    | '/(app)/_layout/activity/timer/'
    | '/(app)/_layout/finance/categories/'
    | '/(app)/_layout/finance/statistic/'
    | '/(app)/_layout/finance/transactions/'
    | '/(app)/_layout/finance/wallet/'
    | '/(app)/_layout/portfolio/crypto/'
    | '/(app)/_layout/portfolio/overview/'
    | '/(app)/_layout/portfolio/stocks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appLayoutRoute: typeof appLayoutRouteWithChildren
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/notes/': {
      id: '/(app)/_layout/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof appLayoutNotesIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/finance/': {
      id: '/(app)/_layout/finance/'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof appLayoutFinanceIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/activity/': {
      id: '/(app)/_layout/activity/'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof appLayoutActivityIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/portfolio/stocks/': {
      id: '/(app)/_layout/portfolio/stocks/'
      path: '/portfolio/stocks'
      fullPath: '/portfolio/stocks'
      preLoaderRoute: typeof appLayoutPortfolioStocksIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/portfolio/overview/': {
      id: '/(app)/_layout/portfolio/overview/'
      path: '/portfolio/overview'
      fullPath: '/portfolio/overview'
      preLoaderRoute: typeof appLayoutPortfolioOverviewIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/portfolio/crypto/': {
      id: '/(app)/_layout/portfolio/crypto/'
      path: '/portfolio/crypto'
      fullPath: '/portfolio/crypto'
      preLoaderRoute: typeof appLayoutPortfolioCryptoIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/finance/wallet/': {
      id: '/(app)/_layout/finance/wallet/'
      path: '/finance/wallet'
      fullPath: '/finance/wallet'
      preLoaderRoute: typeof appLayoutFinanceWalletIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/finance/transactions/': {
      id: '/(app)/_layout/finance/transactions/'
      path: '/finance/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof appLayoutFinanceTransactionsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/finance/statistic/': {
      id: '/(app)/_layout/finance/statistic/'
      path: '/finance/statistic'
      fullPath: '/finance/statistic'
      preLoaderRoute: typeof appLayoutFinanceStatisticIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/finance/categories/': {
      id: '/(app)/_layout/finance/categories/'
      path: '/finance/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof appLayoutFinanceCategoriesIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/activity/timer/': {
      id: '/(app)/_layout/activity/timer/'
      path: '/activity/timer'
      fullPath: '/activity/timer'
      preLoaderRoute: typeof appLayoutActivityTimerIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/activity/log/': {
      id: '/(app)/_layout/activity/log/'
      path: '/activity/log'
      fullPath: '/activity/log'
      preLoaderRoute: typeof appLayoutActivityLogIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/activity/categories/': {
      id: '/(app)/_layout/activity/categories/'
      path: '/activity/categories'
      fullPath: '/activity/categories'
      preLoaderRoute: typeof appLayoutActivityCategoriesIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
  }
}

interface appLayoutRouteChildren {
  appLayoutActivityIndexRoute: typeof appLayoutActivityIndexRoute
  appLayoutFinanceIndexRoute: typeof appLayoutFinanceIndexRoute
  appLayoutNotesIndexRoute: typeof appLayoutNotesIndexRoute
  appLayoutActivityCategoriesIndexRoute: typeof appLayoutActivityCategoriesIndexRoute
  appLayoutActivityLogIndexRoute: typeof appLayoutActivityLogIndexRoute
  appLayoutActivityTimerIndexRoute: typeof appLayoutActivityTimerIndexRoute
  appLayoutFinanceCategoriesIndexRoute: typeof appLayoutFinanceCategoriesIndexRoute
  appLayoutFinanceStatisticIndexRoute: typeof appLayoutFinanceStatisticIndexRoute
  appLayoutFinanceTransactionsIndexRoute: typeof appLayoutFinanceTransactionsIndexRoute
  appLayoutFinanceWalletIndexRoute: typeof appLayoutFinanceWalletIndexRoute
  appLayoutPortfolioCryptoIndexRoute: typeof appLayoutPortfolioCryptoIndexRoute
  appLayoutPortfolioOverviewIndexRoute: typeof appLayoutPortfolioOverviewIndexRoute
  appLayoutPortfolioStocksIndexRoute: typeof appLayoutPortfolioStocksIndexRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appLayoutActivityIndexRoute: appLayoutActivityIndexRoute,
  appLayoutFinanceIndexRoute: appLayoutFinanceIndexRoute,
  appLayoutNotesIndexRoute: appLayoutNotesIndexRoute,
  appLayoutActivityCategoriesIndexRoute: appLayoutActivityCategoriesIndexRoute,
  appLayoutActivityLogIndexRoute: appLayoutActivityLogIndexRoute,
  appLayoutActivityTimerIndexRoute: appLayoutActivityTimerIndexRoute,
  appLayoutFinanceCategoriesIndexRoute: appLayoutFinanceCategoriesIndexRoute,
  appLayoutFinanceStatisticIndexRoute: appLayoutFinanceStatisticIndexRoute,
  appLayoutFinanceTransactionsIndexRoute:
    appLayoutFinanceTransactionsIndexRoute,
  appLayoutFinanceWalletIndexRoute: appLayoutFinanceWalletIndexRoute,
  appLayoutPortfolioCryptoIndexRoute: appLayoutPortfolioCryptoIndexRoute,
  appLayoutPortfolioOverviewIndexRoute: appLayoutPortfolioOverviewIndexRoute,
  appLayoutPortfolioStocksIndexRoute: appLayoutPortfolioStocksIndexRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appLayoutRoute: appLayoutRouteWithChildren,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
